### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Baraa42** [xan-crypto/CurveZero#1]
https://github.com/xan-crypto/CurveZero/blob/d082f394bec403fd91e07db51755f6b9fffa9e62/Core/CZCore.cairo#L90

for authorised_callers() function id suggest adding a mapping in CZCore or TrustedAddy that maps address to 1 if address is an authorised actor instead of writing all if statements.

**Comment by xan-crypto** [comment]
not sure I follow this, ultimately regardless of what you store, you need to compare the caller (any addy) to a list of valid addys (auth list) at the time of call. Not sure how storing a mapping to 1 solves that problem. Can you perhaps add a code snippet, else we can discuss on the weekly call

**Comment by xan-crypto** [comment]
Will close for now. Happy to chat through whenever you want.
