### ISSUE TITLE
Suggestion Check allowance

### ISSUE THREAD

**Issue by Baraa42** [xan-crypto/CurveZero#2]
https://github.com/xan-crypto/CurveZero/blob/d082f394bec403fd91e07db51755f6b9fffa9e62/Core/CZCore.cairo#L142

Would suggest to add a line :

with_attr error_message("Insufficient Allowance "):
        assert_le(Erc20.ERC20_allowances(sender, recipient), amount)
    end

This would help debugging in case of tx failure

**Comment by xan-crypto** [comment]
good point... will add thanks.
